### Problem Statement

"Trips & Travel.Com" company wants to enable and establish a viable business model to expand the customer base. One of the ways to expand the customer base is to introduce a new offering of packages. Currently, there are 5 types of packages the company is offering * Basic, Standard, Deluxe, Super Deluxe, King. Looking at the data of the last year, we observed that 18% of the customers purchased the packages. However, the marketing cost was quite high because customers were contacted at random without looking at the available information. The company is now planning to launch a new product i.e. Wellness Tourism Package. Wellness Tourism is defined as Travel that allows the traveler to maintain, enhance or kick-start a healthy lifestyle, and support or increase one's sense of well-being. However, this time company wants to harness the available data of existing and potential customers to make the marketing expenditure more efficient.

In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('Travel.csv')
df

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

## Data Cleaning

In [3]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [4]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [5]:
df['Gender'] = df['Gender'].replace('Fe Male','Female')
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [6]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [7]:
df['MaritalStatus'] = df['MaritalStatus'].replace('Single','Unmarried')
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

## imputing null values
1. impute median for age column 
2. impute mode for typeofcontract  ----------for categorical feature
3. impute median for duration of pitch ---------------for integer/float values 
4. impute mode for Numberoffollowup as it is descrete feature
5. impute mode for preferedpropertystar
6. impute median for Numberof Trips
7. impute mode for NumberOfChildrenVisiting
8. impute median for MonthlyIncome

In [8]:
#Age
df.Age.fillna(df.Age.median(),inplace=True)

#TypeOfContact
df.TypeofContact.fillna(df.TypeofContact.mode()[0],inplace=True)

#DurationOfPitch
df.DurationOfPitch.fillna(df.DurationOfPitch.median(),inplace=True)

#NumberOfFollowups
df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0],inplace=True)

#PreferredPropertyStar
df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0],inplace=True)

#NumberOfTrips
df.NumberOfTrips.fillna(df.NumberOfTrips.median(),inplace=True)

#NumberOfChildrenVisiting
df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0],inplace=True)

#MonthlyIncome
df.MonthlyIncome.fillna(df.MonthlyIncome.median(),inplace=True)

In [9]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [10]:
df.drop('CustomerID',inplace=True,axis=1)

In [11]:
#creating new col
df['NumberofVisitors'] = df['NumberOfPersonVisiting'] +df['NumberOfChildrenVisiting']
df.drop(['NumberOfPersonVisiting','NumberOfChildrenVisiting'],inplace=True,axis=1)

## Train Test Split

In [12]:
from sklearn.model_selection import train_test_split
X = df.drop('ProdTaken',axis=1)
y = df['ProdTaken']

In [13]:
x_train,x_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=.30)

In [14]:
x_train.shape

(3421, 17)

In [15]:
#Create coloumn transformer w 3 types of transformer
categorial_features = X.select_dtypes(include='object').columns
numerical_features = X.select_dtypes(exclude='object').columns

from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer

st_scalar =StandardScaler()
oh_encoder = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer([
    ('OneHotEncoder',oh_encoder,categorial_features),
    ('StandardScalar',st_scalar,numerical_features)
])

In [16]:
x_train = preprocessor.fit_transform(x_train)
x_test = preprocessor.transform(x_test)

In [17]:
pd.DataFrame(x_train)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,-0.714031,-0.649789,0.280718,-0.727208,-1.217370,-0.632714,1.409081,0.781435,0.460318,-0.067869
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,-0.714031,-0.527737,-0.719632,1.768057,1.504605,-0.632714,1.409081,-1.279697,-1.005668,-0.777901
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.161582,1.281068,1.768057,-0.672975,1.580492,-0.046813,0.781435,-1.209722,-0.067869
3,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.470853,-0.771841,0.280718,0.520424,-0.128580,1.580492,-0.046813,0.781435,-0.017750,0.642163
4,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.527737,1.281068,0.520424,2.593396,-0.632714,0.681134,-1.279697,-0.423411,-0.067869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3416,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.649789,1.281068,-0.727208,-0.672975,-0.632714,-1.502707,0.781435,-0.531926,0.642163
3417,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.470853,-0.893893,-0.719632,1.768057,-1.217370,-0.632714,1.409081,0.781435,1.512744,-0.067869
3418,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.470853,1.547143,0.280718,-0.727208,2.049001,-0.632714,-0.774760,0.781435,-0.357400,0.642163
3419,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.470853,1.791246,1.281068,-0.727208,-0.128580,-0.632714,-1.502707,0.781435,-0.250765,0.642163
3420,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.714031,-0.771841,0.280718,-0.727208,-1.217370,1.580492,-0.046813,-1.279697,-1.071680,-1.487933

## Xgboost Classifier Training

In [19]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,classification_report,precision_score, recall_score, f1_score, roc_auc_score,roc_curve

In [20]:
model = XGBClassifier()
model.fit(x_train,y_train) #model training

y_train_pred = model.predict(x_train)
y_test_pred = model.predict(x_test)

#training set Performance
model_train_accuracy = accuracy_score(y_train,y_train_pred)
model_train_f1 = f1_score(y_train,y_train_pred,average='weighted')
model_train_precision = precision_score(y_train,y_train_pred)
model_train_recall = recall_score(y_train,y_train_pred)
model_train_rocauc_score = roc_auc_score(y_train,y_train_pred)

#test set performance
model_test_accuracy = accuracy_score(y_test,y_test_pred)
model_test_f1 = f1_score(y_test,y_test_pred,average='weighted')
model_test_precision = precision_score(y_test,y_test_pred)
model_test_recall = recall_score(y_test,y_test_pred)
model_test_rocauc_score = roc_auc_score(y_test,y_test_pred)


print('Model Performance for training set')
print('Accuracy: {:.4f}'.format(model_train_accuracy))
print('F1 Score: {:.4f}'.format(model_train_f1))
print('precision: {:.4f}'.format(model_train_precision))
print('Recall: {:.4f}'.format(model_train_recall))
print('Roc Auc Score: {:.4f}'.format(model_train_rocauc_score))

print('--------------------------------------------')

print('Model Performance for testing set')
print('Accuracy: {:.4f}'.format(model_test_accuracy))
print('F1 Score: {:.4f}'.format(model_test_f1))
print('precision: {:.4f}'.format(model_test_precision))
print('Recall: {:.4f}'.format(model_test_recall))
print('Roc Auc Score: {:.4f}'.format(model_test_rocauc_score))

print('='*35)
print('\n')

Model Performance for training set
Accuracy: 0.9997
F1 Score: 0.9997
precision: 1.0000
Recall: 0.9985
Roc Auc Score: 0.9992
--------------------------------------------
Model Performance for testing set
Accuracy: 0.9332
F1 Score: 0.9308
precision: 0.8860
Recall: 0.7372
Roc Auc Score: 0.8577
===================================

### HyperParameter Tunning

In [21]:
xg_param ={"learning_rate": [0.1, 0.01,0.10],
                                "max_depth": [5, 8, 12, 20,22, 30],
                                "n_estimators": [100, 200, 300],
                                "colsample_bytree": [0.5, 0.8, 1, 0.3, 0.4]}

In [22]:
random_cv=[
    ('Xgboost',XGBClassifier(),xg_param)
]

In [23]:
from sklearn.model_selection import RandomizedSearchCV
model_param = {}
for name,model,param in random_cv:
    random = RandomizedSearchCV(estimator=model,
                               param_distributions=param,
                               n_iter=100,
                               cv=3,
                               verbose=2,
                               n_jobs=-1)
    random.fit(x_train,y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"---------------Best Param----------------{model_name}")
    print(model_param[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
---------------Best Param----------------Xgboost
{'n_estimators': 300, 'max_depth': 22, 'learning_rate': 0.1, 'colsample_bytree': 0.5}

In [24]:
models = {
    'Xgboost':XGBClassifier(n_estimators=300, max_depth = 20, learning_rate =0.1, colsample_bytree = 0.8)
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train,y_train)  #train model
    
y_train_pred = model.predict(x_train)
y_test_pred = model.predict(x_test)

#training set Performance
model_train_accuracy = accuracy_score(y_train,y_train_pred)
model_train_f1 = f1_score(y_train,y_train_pred,average='weighted')
model_train_precision = precision_score(y_train,y_train_pred)
model_train_recall = recall_score(y_train,y_train_pred)
model_train_rocauc_score = roc_auc_score(y_train,y_train_pred)

#test set performance
model_test_accuracy = accuracy_score(y_test,y_test_pred)
model_test_f1 = f1_score(y_test,y_test_pred,average='weighted')
model_test_precision = precision_score(y_test,y_test_pred)
model_test_recall = recall_score(y_test,y_test_pred)
model_test_rocauc_score = roc_auc_score(y_test,y_test_pred)


print('Model Performance for training set')
print('Accuracy: {:.4f}'.format(model_train_accuracy))
print('F1 Score: {:.4f}'.format(model_train_f1))
print('precision: {:.4f}'.format(model_train_precision))
print('Recall: {:.4f}'.format(model_train_recall))
print('Roc Auc Score: {:.4f}'.format(model_train_rocauc_score))

print('--------------------------------------------')

print('Model Performance for testing set')
print('Accuracy: {:.4f}'.format(model_test_accuracy))
print('F1 Score: {:.4f}'.format(model_test_f1))
print('precision: {:.4f}'.format(model_test_precision))
print('Recall: {:.4f}'.format(model_test_recall))
print('Roc Auc Score: {:.4f}'.format(model_test_rocauc_score))

print('='*35)
print('\n')

Model Performance for training set
Accuracy: 1.0000
F1 Score: 1.0000
precision: 1.0000
Recall: 1.0000
Roc Auc Score: 1.0000
--------------------------------------------
Model Performance for testing set
Accuracy: 0.9496
F1 Score: 0.9475
precision: 0.9505
Recall: 0.7701
Roc Auc Score: 0.8804
===================================