## Car Price Prediction

## 1) Problem statement.
This dataset comprises used cars sold on cardehko.com in India as well as important features
of these cars.
If user can predict the price of the car based on input features.
Prediction results can be used to give new seller the price suggestion based on market
condition.

## 2) Data Collection.
The Dataset is collected from scrapping from cardheko webiste
The data consists of 13 column and 15411 rows.

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('cardekho_imputated.csv',index_col=[0])
df

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [3]:
df.drop('car_name', axis=1, inplace=True)
df.drop('brand', axis=1, inplace=True)

## Train Test Split

In [4]:
from sklearn.model_selection import train_test_split
X= df.drop('selling_price',axis=1)
y = df['selling_price']

In [5]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['model'] = le.fit_transform(X['model'])

In [7]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [8]:
num_feature =X.select_dtypes(exclude='object').columns
cat_feature = ['seller_type','fuel_type','transmission_type']

from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer

cat_encode = OneHotEncoder()
num_encode= StandardScaler()

preprocessor = ColumnTransformer([
    ('OneHotEncoder',cat_encode,cat_feature),
    ('StandardScalar',num_encode,num_feature)
],remainder='passthrough')

In [9]:
X = preprocessor.fit_transform(X)

In [10]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.30,random_state=42)

## Model Training and Selection

In [13]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,root_mean_squared_error,mean_absolute_error,mean_squared_error

In [14]:
def evaluate_model(true,predicted):
    r2 = r2_score(true,predicted)
    mae = mean_absolute_error(true,predicted)
    mse = mean_squared_error(true,predicted)
    rmse = root_mean_squared_error(true,predicted)
    return r2,mae,mse,rmse

In [15]:
model = XGBRegressor()
model.fit(X_train,y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

model_train_r2,model_train_mae,model_train_mse,model_train_rmse = evaluate_model(y_train,y_train_pred)
model_test_r2,model_test_mae,model_test_mse,model_test_rmse = evaluate_model(y_test,y_test_pred)

print('model performance for training set')
print(f"Root Mean Squared error {model_train_rmse:.4f}")
print(f"Mean Squared error {model_train_mse:.4f}")
print(f"Mean Absolute error {model_train_mae:.4f}")
print(f"R2 Square {model_train_r2:.4f}")

print('='*35)

print('model performance for testing set')
print(f"Root Mean Squared error {model_test_rmse:.4f}")
print(f"Mean Squared error {model_test_mse:.4f}")
print(f"Mean Absolute error {model_test_mae:.4f}")
print(f"R2 Square {model_test_r2:.4f}")

print('\n')

model performance for training set
Root Mean Squared error 83875.4922
Mean Squared error 7035098112.0000
Mean Absolute error 59797.7109
R2 Square 0.9914
===================================
model performance for testing set
Root Mean Squared error 427336.0000
Mean Squared error 182616047616.0000
Mean Absolute error 109587.3359
R2 Square 0.7572

## Hyperparameter Tunning

In [16]:
xgboost_params = {"learning_rate": [0.1, 0.01,0.10,0.001],
                "max_depth": [5, 8, 12, 20, 30],
                "n_estimators": [100, 200, 300],
                "colsample_bytree": [0.5, 0.8, 1, 0.3, 0.4]}

In [17]:
from sklearn.model_selection import RandomizedSearchCV

random = RandomizedSearchCV(estimator=XGBRegressor(),param_distributions=xgboost_params,n_iter=100,cv=3,n_jobs=-1)

random.fit(X_train,y_train)
print(random.best_params_)

{'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.1, 'colsample_bytree': 0.4}

In [18]:
model = XGBRegressor(n_estimators=300, max_depth=5, learning_rate=0.1, colsample_bytree=0.4)
model.fit(X_train,y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

model_train_r2,model_train_mae,model_train_mse,model_train_rmse = evaluate_model(y_train,y_train_pred)
model_test_r2,model_test_mae,model_test_mse,model_test_rmse = evaluate_model(y_test,y_test_pred)

print('model performance for training set')
print(f"Root Mean Squared error {model_train_rmse:.4f}")
print(f"Mean Squared error {model_train_mse:.4f}")
print(f"Mean Absolute error {model_train_mae:.4f}")
print(f"R2 Square {model_train_r2:.4f}")

print('='*35)

print('model performance for testing set')
print(f"Root Mean Squared error {model_test_rmse:.4f}")
print(f"Mean Squared error {model_test_mse:.4f}")
print(f"Mean Absolute error {model_test_mae:.4f}")
print(f"R2 Square {model_test_r2:.4f}")

print('\n')

model performance for training set
Root Mean Squared error 113370.8984
Mean Squared error 12852960256.0000
Mean Absolute error 74749.3984
R2 Square 0.9843
===================================
model performance for testing set
Root Mean Squared error 272472.0625
Mean Squared error 74241024000.0000
Mean Absolute error 104814.3594
R2 Square 0.9013